blueprint:
  name: Lutron Pico 2 Button Paddle Actions (1P)
  description: Different Actions on Short, Double Click, and Continuous Hold (Dimming) for Paddle Picos.
  domain: automation

  input:
    pico_id:
      name: Lutron Pico
      description: The Lutron Pico used to trigger the automations
      selector:
        device:
          model: PJ2-1P-GXX (PaddleSwitchPico)
          multiple: false
    target_lights:
      name: Target Lights
      description: The lights to be dimmed during a hold.
      selector:
        target:
          entity:
            domain: light
    short_click_action_on:
      name: On Button Short Click
      default: []
      selector:
        action: {}
    short_click_action_off:
      name: Off Button Short Click
      default: []
      selector:
        action: {}
    double_click_action_on:
      name: On Button Double Click
      default: []
      selector:
        action: {}
    double_click_action_off:
      name: Off Button Double Click
      default: []
      selector:
        action: {}
    delay_click:
      name: Double Click Delay
      description: Time in ms for double click detection.
      default: 250
      selector:
        number:
          min: 100.0
          max: 1000.0
          unit_of_measurement: milliseconds
          step: 1.0
          mode: slider
    delay_hold:
      name: Hold Delay
      description: Time to wait before starting the dimming loop. Reduced for faster response.
      default: 400
      selector:
        number:
          min: 100.0
          max: 2000.0
          unit_of_measurement: milliseconds
          step: 1.0
          mode: slider

trigger:
- platform: event
  event_type: lutron_caseta_button_event
  event_data:
    device_id: !input pico_id
    leap_button_number: 0
    action: press
  id: on_pressed
- platform: event
  event_type: lutron_caseta_button_event
  event_data:
    device_id: !input pico_id
    leap_button_number: 2
    action: press
  id: off_pressed

action:
- variables:
    hold_ms: !input delay_hold
    tap_ms: !input delay_click
    pico_id: !input pico_id
- choose:
  - conditions:
    - condition: trigger
      id: on_pressed
    sequence:
    - wait_for_trigger:
      - platform: event
        event_type: lutron_caseta_button_event
        event_data:
          device_id: !input pico_id
          leap_button_number: 0
          action: release
      timeout:
        milliseconds: '{{ hold_ms }}'
    - choose:
      - conditions:
        - condition: template
          value_template: '{{ wait.trigger == none }}'
        sequence: # SMOOTH DIMMING ON
        - repeat:
            while:
            - condition: template
              value_template: '{{ repeat.index < 40 }}' # Increased limit for smaller steps
            sequence:
            - action: light.turn_on
              target: !input target_lights
              data:
                brightness_step_pct: 5
            - wait_for_trigger:
              - platform: event
                event_type: lutron_caseta_button_event
                event_data:
                  device_id: !input pico_id
                  leap_button_number: 0
                  action: release
              timeout:
                milliseconds: 100 # Faster polling for smoothness
            - condition: template
              value_template: '{{ wait.trigger != none }}'
            - stop: "Button released"
      default: # Double/Short Click detection
      - wait_for_trigger:
        - platform: event
          event_type: lutron_caseta_button_event
          event_data:
            device_id: !input pico_id
            leap_button_number: 0
            action: press
        timeout:
          milliseconds: '{{ tap_ms }}'
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ wait.trigger == none }}'
          sequence: !input short_click_action_on
        default: !input double_click_action_on

  - conditions:
    - condition: trigger
      id: off_pressed
    sequence:
    - wait_for_trigger:
      - platform: event
        event_type: lutron_caseta_button_event
        event_data:
          device_id: !input pico_id
          leap_button_number: 2
          action: release
      timeout:
        milliseconds: '{{ hold_ms }}'
    - choose:
      - conditions:
        - condition: template
          value_template: '{{ wait.trigger == none }}'
        sequence: # SMOOTH DIMMING OFF
        - repeat:
            while:
            - condition: template
              value_template: '{{ repeat.index < 40 }}'
            sequence:
            - action: light.turn_on
              target: !input target_lights
              data:
                brightness_step_pct: -5
            - wait_for_trigger:
              - platform: event
                event_type: lutron_caseta_button_event
                event_data:
                  device_id: !input pico_id
                  leap_button_number: 2
                  action: release
              timeout:
                milliseconds: 100 # Faster polling for smoothness
            - condition: template
              value_template: '{{ wait.trigger != none }}'
            - stop: "Button released"
      default:
      - wait_for_trigger:
        - platform: event
          event_type: lutron_caseta_button_event
          event_data:
            device_id: !input pico_id
            leap_button_number: 2
            action: press
        timeout:
          milliseconds: '{{ tap_ms }}'
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ wait.trigger == none }}'
          sequence: !input short_click_action_off
        default: !input double_click_action_off
mode: restart
