blueprint:
  name: Lutron Pico 5 Button Hybrid (3BRL)
  description: |
    Combines advanced action capabilities with smooth dimming.
    
    FEATURES:
    - Supports Short, Long, and Double Clicks for On, Off, and Middle buttons.
    - HYBRID UP/DOWN BEHAVIOR: 
      1. If a 'Target Light' is selected, Up/Down buttons perform smooth continuous dimming (hold to dim).
      2. If 'Target Light' is empty, Up/Down buttons trigger their custom Short/Long actions.
  domain: automation

  input:
    pico_id:
      name: Lutron Pico
      description: The Lutron Pico used to trigger the automations
      selector:
        device:
          model: PJ2-3BRL-GXX-X01 (Pico3ButtonRaiseLower)
          multiple: false
    
    # --- DIMMING CONFIGURATION ---
    target_light:
      name: Target Light for Dimming (Optional)
      description: >
        If selected, Up/Down buttons will smoothly dim this light(s) and ignore the custom actions below. 
        If left empty, Up/Down buttons will use the Custom Actions defined below.
      default: {}
      selector:
        entity:
          filter:
            domain: light
          multiple: true
    dimming_step:
      name: Dimming Step Percentage
      description: Percentage to change brightness per step when holding Up/Down (Only if Target Light is set).
      default: 5
      selector:
        number:
          min: 1
          max: 25
          unit_of_measurement: percent
    
    # --- CUSTOM ACTIONS (ORIGINAL) ---
    short_click_action_on:
      name: On Button Short Click
      description: Action for single short click
      default: []
      selector:
        action: {}
    short_click_action_up:
      name: Up Button Short Click
      description: Action for single short click (Ignored if Target Light is set)
      default: []
      selector:
        action: {}
    short_click_action_stop:
      name: Middle Button Short Click
      description: Action for single short click
      default: []
      selector:
        action: {}
    short_click_action_down:
      name: Down Button Short Click
      description: Action for single short click (Ignored if Target Light is set)
      default: []
      selector:
        action: {}
    short_click_action_off:
      name: Off Button Short Click
      description: Action for single short click
      default: []
      selector:
        action: {}
        
    long_click_action_on:
      name: On Button Long Click
      description: Action for long click
      default: []
      selector:
        action: {}
    long_click_action_up:
      name: Up Button Long Click
      description: Action for long click (Ignored if Target Light is set)
      default: []
      selector:
        action: {}
    long_click_action_stop:
      name: Middle Button Long Click
      description: Action for long click
      default: []
      selector:
        action: {}
    long_click_action_down:
      name: Down Button Long Click
      description: Action for long click (Ignored if Target Light is set)
      default: []
      selector:
        action: {}
    long_click_action_off:
      name: Off Button Long Click
      description: Action for long click
      default: []
      selector:
        action: {}
        
    double_click_action_on:
      name: On Button Double Click
      description: Action for double click
      default: []
      selector:
        action: {}
    double_click_action_stop:
      name: Middle Button Double Click
      description: Action for double click
      default: []
      selector:
        action: {}
    double_click_action_off:
      name: Off Button Double Click
      description: Action for double click
      default: []
      selector:
        action: {}
        
    delay_click:
      name: Double Click Delay
      description: The time in milliseconds used for the double click detection
      default: 250
      selector:
        number:
          min: 100
          max: 1000
          unit_of_measurement: milliseconds
          step: 1
          mode: slider
    delay_hold:
      name: Hold Delay
      description: The time in milliseconds used for the hold detection
      default: 400
      selector:
        number:
          min: 100
          max: 1000
          unit_of_measurement: milliseconds
          step: 1
          mode: slider

trigger:
  - platform: device
    device_id: !input pico_id
    domain: lutron_caseta
    type: press
    subtype: 'on'
    id: on_pressed
  - platform: device
    device_id: !input pico_id
    domain: lutron_caseta
    type: press
    subtype: raise
    id: up_pressed
  - platform: device
    device_id: !input pico_id
    domain: lutron_caseta
    type: press
    subtype: stop
    id: stop_pressed
  - platform: device
    device_id: !input pico_id
    domain: lutron_caseta
    type: press
    subtype: lower
    id: down_pressed
  - platform: device
    device_id: !input pico_id
    domain: lutron_caseta
    type: press
    subtype: 'off'
    id: off_pressed    

action:
  - variables:
      hold_ms: !input delay_hold
      tap_ms: !input delay_click
      step_pct: !input dimming_step
      target_light: !input target_light
      pico_id: "{{ trigger.event.data.device_id }}"

  - choose:
      # --- ON BUTTON (Supports Double Click) ---
      - conditions:
          - condition: trigger
            id: on_pressed
        sequence:
          - wait_for_trigger:
              - platform: device
                device_id: !input pico_id
                domain: lutron_caseta
                type: release
                subtype: "on"
            timeout:
              milliseconds: "{{ hold_ms }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ wait.trigger == none }}"
                sequence: !input long_click_action_on
            default:
              - wait_for_trigger:
                  - platform: device
                    device_id: !input pico_id
                    domain: lutron_caseta
                    type: press
                    subtype: "on"
                timeout:
                  milliseconds: "{{ tap_ms }}"
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ wait.trigger == none }}"
                    sequence: !input short_click_action_on
                default: !input double_click_action_on

      # --- UP BUTTON (Hybrid: Dimming OR Action) ---
      - conditions:
          - condition: trigger
            id: up_pressed
        sequence:
          - choose:
              # Option 1: Continuous Dimming (if light is selected)
              - conditions:
                  - condition: template
                    value_template: "{{ target_light != none }}"
                sequence:
                  - repeat:
                      sequence:
                        - service: light.turn_on
                          target:
                            entity_id: !input target_light
                          data:
                            brightness_step_pct: "{{ step_pct }}"
                            transition: 0.5
                        - wait_for_trigger:
                            - platform: device
                              device_id: !input pico_id
                              domain: lutron_caseta
                              type: release
                              subtype: raise
                          timeout:
                            milliseconds: 500
                          continue_on_timeout: true
                        - if:
                            - condition: template
                              value_template: "{{ wait.remaining > 0 }}"
                          then:
                            - stop: 
                      until:
                        - condition: numeric_state
                          entity_id: !input target_light
                          attribute: brightness
                          above: 254
              # Option 2: Standard Actions (Short/Long)
                default:
                  - wait_for_trigger:
                      - platform: device
                        device_id: !input pico_id
                        domain: lutron_caseta
                        type: release
                        subtype: raise
                    timeout:
                      milliseconds: "{{ hold_ms }}"
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ wait.trigger == none }}"
                        sequence: !input long_click_action_up
                    default: !input short_click_action_up

      # --- STOP BUTTON (Supports Double Click) ---
      - conditions:
          - condition: trigger
            id: stop_pressed
        sequence:
          - wait_for_trigger:
              - platform: device
                device_id: !input pico_id
                domain: lutron_caseta
                type: release
                subtype: stop
            timeout:
              milliseconds: "{{ hold_ms }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ wait.trigger == none }}"
                sequence: !input long_click_action_stop
            default:
              - wait_for_trigger:
                  - platform: device
                    device_id: !input pico_id
                    domain: lutron_caseta
                    type: press
                    subtype: stop
                timeout:
                  milliseconds: "{{ tap_ms }}"
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ wait.trigger == none }}"
                    sequence: !input short_click_action_stop
                default: !input double_click_action_stop

      # --- DOWN BUTTON (Hybrid: Dimming OR Action) ---
      - conditions:
          - condition: trigger
            id: down_pressed
        sequence:
          - choose:
              # Option 1: Continuous Dimming
              - conditions:
                  - condition: template
                    value_template: "{{ target_light != none }}"
                sequence:
                  - repeat:
                      sequence:
                        - service: light.turn_on
                          target:
                            entity_id: !input target_light
                          data:
                            brightness_step_pct: "{{ step_pct * -1 }}"
                            transition: 0.5
                        - wait_for_trigger:
                            - platform: device
                              device_id: !input pico_id
                              domain: lutron_caseta
                              type: release
                              subtype: lower
                          timeout:
                            milliseconds: 500
                          continue_on_timeout: true
                        - if:
                            - condition: template
                              value_template: "{{ wait.remaining > 0 }}"
                          then:
                            - stop: 
                      until:
                        - condition: numeric_state
                          entity_id: !input target_light
                          attribute: brightness
                          below: 1
              # Option 2: Standard Actions
                default:
                  - wait_for_trigger:
                      - platform: device
                        device_id: !input pico_id
                        domain: lutron_caseta
                        type: release
                        subtype: lower
                    timeout:
                      milliseconds: "{{ hold_ms }}"
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ wait.trigger == none }}"
                        sequence: !input long_click_action_down
                    default: !input short_click_action_down

      # --- OFF BUTTON (Supports Double Click) ---
      - conditions:
          - condition: trigger
            id: off_pressed
        sequence:
          - wait_for_trigger:
              - platform: device
                device_id: !input pico_id
                domain: lutron_caseta
                type: release
                subtype: "off"
            timeout:
              milliseconds: "{{ hold_ms }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ wait.trigger == none }}"
                sequence: !input long_click_action_off
            default:
              - wait_for_trigger:
                  - platform: device
                    device_id: !input pico_id
                    domain: lutron_caseta
                    type: press
                    subtype: "off"
                timeout:
                  milliseconds: "{{ tap_ms }}"
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ wait.trigger == none }}"
                    sequence: !input short_click_action_off
                default: !input double_click_action_off

mode: restart
